mrd_parameters:
  blast_phenotype_filter:
    allowed_categories:
    - BLAST_HIGH
    - BLAST_MODERATE
    apply_to_eln: true
    apply_to_flo: true
    apply_to_jf: true
    d2_normalization: 109.28
    d2_threshold_high: 25.8
    d2_threshold_moderate: 19.03
    enabled: false
    high_threshold: 2.2
    linear_weight: 0.17
    mahal_boost_factor: 1.03
    mahal_weight: 0.56
    marker_weights:
      CD117: 1.0
      CD13: 0.8
      CD33: 0.15
      CD34: 1.4
      CD45: -0.1
      HLA-DR: 0.5
      SSC: -3.0
    moderate_threshold: 1.5
    nbm_cov_max_cells: 120000
    nbm_mincovdet_max_cells: 30000
    nbm_stats_max_cells: 250000
    purity_modulation_power: 0.11
    purity_relax_factor: 0.08
    purity_strict_above: 0.988
    purity_threshold_override: true
    scoring_method: linear
    weak_threshold: 1.0
  condition_patho: Pathologique
  condition_sain: Sain
  eln_standards:
    clinical_positivity_pct: 0.1
    min_cluster_events: 50
  enabled: true
  method: all
  method_flo:
    normal_marrow_multiplier: 5.0
  method_jf:
    max_normal_marrow_pct: 0.1
    min_patho_cells_pct: 50.0
